/**:
  ros__parameters:
    wheelRadius: 4.06 # en cm
    pasStepper: 1.8 # degrÃ©s par step
    ticsPerStep: 32 # de combien augmente le compteur (du moteur) de position phidget par steps
    stepper: 4   # port du stepper on the phidget hub
    hub : 627520  # serial number du hub
